
server:
  port: 4005
spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/duflon
    username: postgres
  jackson:
    time-zone: IST
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
         lob:
          non_contextual_creation: true
  application:
    name: Duflon
        
pdf:
  downloadPdfFile: E:\\temp\\
  exeUrl: C:\\wkhtmltopdf\\bin\\wkhtmltopdf
Ap:
  #assessmentURL: http://assess.armezo.com/iRecruit/
  assessmentURL: https://assess.armezo.com/Armezo/
  dmsURL: http://staging.dmssales.co.in:9003/iRecruit/
  adminLink: http://staging.dmssales.co.in:9003/iRecruit/
  candLink: http://staging.dmssales.co.in:9003/iRecruit/
  url : https://www.duflon.com/